### ISSUE TITLE
Do not set show sources list twice

### ISSUE THREAD

**Issue by tashrifbillah** [AMP-SCZ/lochness#44]
I don't remember when we set the default:

https://github.com/AMP-SCZ/lochness/blob/67c93fef823329a45cf71037098015c1d8cb9e13/scripts/sync.py#L64-L65

But I do not think that is right. The default should be none. Meanwhile, setting such prints the source list twice after `--source` which is not so tidy:

>  --hdd HDD [HDD ...]   choose hdds to sync
  --source {xnat,beiwe,redcap,mindlamp,dropbox,box,mediaflux,daris,rpms,icognition,onlinescoring,upenn} [{xnat,beiwe,redcap,mindlamp,dropbox,box,mediaflux,daris,rpms,icognition,onlinescoring,upenn} ...]
                        Sources to sync
  --continuous          Continuously download data

@kcho

**Comment by kcho** [comment]
This is the original design by the `harvard-nrg/lochness`. For Pronet & Prescient, we are providing list of sources, since we need to specify the main database to populate the `metadata.csv`, either from REDCap or RPMS. I'm with you in removing the `default` option for this argument.

**Comment by tashrifbillah** [comment]
Sorry, it was not an issue with default. It is by argparse design. I have devised a fix anyway.
