### ISSUE TITLE
dpanonymize.ModuleDetectionError: Module is not detected

### ISSUE THREAD

**Issue by tashrifbillah** [AMP-SCZ/lochness#46]
```bash
Traceback (most recent call last):
  File "/home/tb571/miniconda3/bin/sync.py", line 176, in <module>
    main()
  File "/home/tb571/miniconda3/bin/sync.py", line 132, in main
    do(args, Lochness)
  File "/home/tb571/miniconda3/bin/sync.py", line 163, in do
    dpanonymize.lock_lochness(Lochness, pii_table_loc=Lochness['pii_table'])
  File "/home/tb571/miniconda3/lib/python3.8/site-packages/dpanonymize/__init__.py", line 191, in lock_lochness
    file_object.anonymize(**kwargs)
  File "/home/tb571/miniconda3/lib/python3.8/site-packages/dpanonymize/__init__.py", line 72, in anonymize
    raise ModuleDetectionError(
dpanonymize.ModuleDetectionError: Module is not detected: (dtype=AD00451)
```

What is this really and why is it trying to detect a module named after my subject ID? Isn't there a way to skip anonymization and just download data peacefully using current lochness?

**Comment by tashrifbillah** [comment]
I think I found the reason--lochness `BIDS=True/False` downloads do not match with that expected by dpanonymize:

https://github.com/AMP-SCZ/dpanonymize/blob/49282b5c67ca1f88e7a651bc724e639b97e819d9/dpanonymize/__init__.py#L186-L191

Hence, the latter, instead of finding modules, finds subject ID folders. This calls for a thorough investigation!

**Comment by tashrifbillah** [comment]
Can we not hook up this line to a top-level `deidentify` flag so anonymization is skipped entirely:

https://github.com/AMP-SCZ/lochness/blob/d67839878f991eb7e71ebacec8777d8d0ad7b8ad/scripts/sync.py#L164

**Comment by kcho** [comment]
> I think I found the reason--lochness `BIDS=True/False` downloads do not match with that expected by dpanonymize:
> 
> https://github.com/AMP-SCZ/dpanonymize/blob/49282b5c67ca1f88e7a651bc724e639b97e819d9/dpanonymize/__init__.py#L186-L191
> 
> Hence, the latter, instead of finding modules, finds subject ID folders. This calls for a thorough investigation!

From the error message, it seems like you have used `pip` installation for `dpanonymize` (`/home/tb571/miniconda3/lib/python3.8/site-packages/dpanonymize`) `pip` version is not the most recent branch of `dpanonymize`. 
Would you please test with the most recent commit of `dpanonymize` by manual `git clone` and by adding the path to the `PYTHONPATH` please? 

Or if you have cloned the `dpanonymize`, which commit version are you using to test the PHOENIX BIDS structure? And see if it returns the same error? Also please share me your PHOENIX output tree structure, so I can check how the structure pulled by lochness looks.

**Comment by kcho** [comment]
As you've highlighted in the PR https://github.com/AMP-SCZ/lochness/pull/47/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7, for the quick deployment of the lochenss and dpanonymize for Pronet and Prescient, I'm not going to guide them to install `lochness` and `dpanonymize` with `pip install`, but to use `git clone` and add it to the path. Of course I'd like to move to `pypi` once things are ready, but operational model comes first for our project.

**Comment by tashrifbillah** [comment]
Thank you, I'll try again.

What is your idea about [this](https://github.com/AMP-SCZ/lochness/issues/46#issuecomment-921918552) comment?

**Comment by tashrifbillah** [comment]
> BIDS: False

```bash
RED-PHOENIX/PROTECTED/FAKE_HK/HK95726/
└── surveys
    └── raw
        └── HK95726.FAKE_HK.json
RED-PHOENIX/PROTECTED/FAKE_HK/HK98534/
└── surveys
    └── raw
        └── HK98534.FAKE_HK.json
RED-PHOENIX/PROTECTED/FAKE_LA/LA10782/
└── surveys
    └── raw
        └── LA10782.FAKE_LA.json
RED-PHOENIX/PROTECTED/FAKE_LA/LA24153/
└── surveys
    └── raw
        └── LA24153.FAKE_LA.json
```

**Comment by kcho** [comment]
> If they are, although I used deidentify:True, why are the GENERAL ones empty?

The `deidentify` option in the `config.yml` is for `lochness.redcap.sync` to avoid pulling any field labelled as `deidentify==True` within the REDCap field settings.

**Comment by kcho** [comment]
> Please confirm they are the expected ones.
+ BIDS / non-BIDS structures look correct.

**Comment by kcho** [comment]
> Can we not hook up this line to a top-level `deidentify` flag so anonymization is skipped entirely:
> 
> https://github.com/AMP-SCZ/lochness/blob/d67839878f991eb7e71ebacec8777d8d0ad7b8ad/scripts/sync.py#L164

Sounds good. I'll work on it on a separate branch soon.

**Comment by kcho** [comment]
> Kevin, can you address my [concern](https://github.com/AMP-SCZ/lochness/issues/46#issuecomment-922505474):
> 
> > I thought the PROTECTED surveys will be anonymized and put in GENERAL surveys.
> > (Probably we went over this during dpanonymize review but I forget)

Yes, this is the case when we use `dpanonymize` to deidentify surveys. However, the `lochness.redcap.sync` with `deidentify: True` in the `config.yml` does not put survey data under GENERAL It is because there will be fields that DPACC may want to further process, for example, there have been discussions about how to change a specific date to days from a pseudorandom date. This functionality is not supported by `REDCap` so the current design opens a possibility of adding these functionalities in `dpanonymize`.

**Comment by tashrifbillah** [comment]
So is dpanonymize still a placeholder i.e. input to and output from it are the same?

**Comment by kcho** [comment]
> So is dpanonymize still a placeholder i.e. input to and output from it are the same?
> 
> https://github.com/AMP-SCZ/lochness/blob/d67839878f991eb7e71ebacec8777d8d0ad7b8ad/scripts/sync.py#L164

Correct. In `create_lochness_template.py` we create a template `pii_convert.csv` to be linked with the `lochness`, which looks like below. Since the `pii_label_string` column is just arbitrary strings to be edited in future, `dpanonymize` for survey outputs the same file as the input file.

**Comment by tashrifbillah** [comment]
> dpanonymize for survey outputs the same file as the input file.

Where is that output written?

**Comment by kcho** [comment]
> > dpanonymize for survey outputs the same file as the input file.
> 
> Where is that output written?

under GENERAL

**Comment by tashrifbillah** [comment]
Again, my [data trees](https://github.com/AMP-SCZ/lochness/issues/46#issuecomment-922505474) do not have the output files under GENERAL!

**Comment by kcho** [comment]
> Again, my [data trees](https://github.com/AMP-SCZ/lochness/issues/46#issuecomment-922505474) do not have the output files under GENERAL!

Sorry I thought you were testing the `deidentify: True` option. Let me test on my side as well.
Which `dpanonymize` commit version are you using?

**Comment by tashrifbillah** [comment]
Please revisit https://github.com/AMP-SCZ/lochness/issues/46#issuecomment-922505474 where I have also provided my config file.

> Which dpanonymize commit version are you using?

This installation uses current master:
https://github.com/AMP-SCZ/lochness/blob/f8bdba0da8855aaacf9385143e94917a5ba2fab3/setup.py#L18

Which is what I am using.

**Comment by kcho** [comment]
> Please revisit [#46 (comment)](https://github.com/AMP-SCZ/lochness/issues/46#issuecomment-922505474) where I have also provided my config file.
> 
> > Which dpanonymize commit version are you using?
> 
> This installation uses current master:
> https://github.com/AMP-SCZ/lochness/blob/f8bdba0da8855aaacf9385143e94917a5ba2fab3/setup.py#L18
> 
> Which is what I am using.


I think there is a chance that the error of not saving files under GENERAL, may come from the version of the `dpanonymize` being the old one, because I've just tested with `dpanonymize`: 49282b5c67ca1f88e7a651bc724e639b97e819d9, and it's saving files under `GENERAL`.

I think your `config.yml` looks fine. But it's quite difficult for me to debug it in the exact same environment as on your system unless I have access to the system that you're using. Are you testing these under ERIS or cluster to which I can have an access to?

**Comment by tashrifbillah** [comment]
We have the same commit!

My work is in a shared environment already:

```bash
# install a trustworthy lochness
cd /data/predict/
source min3-lochness/bin/activate
conda create -y -n kcho-anon python=3.6
conda activate kcho-anon

# install lochness kcho/pronet branch
pip install git+https://github.com/AMP-SCZ/lochness.git@f8bdba0

# run pipeline
/data/predict/tb571_lochness_test/run_synch.sh

# observe data trees
tree tb571_lochness_test/RED-PHOENIX
```

**Comment by kcho** [comment]
> We have the same commit!
> 
> My work is in a shared environment already:
> 
> ```shell
> # install a trustworthy lochness
> cd /data/predict/
> source min3-lochness/bin/activate
> conda create -y -n kcho-anon python=3.6
> conda activate kcho-anon
> 
> # install lochness kcho/pronet branch
> pip install git+https://github.com/AMP-SCZ/lochness.git@f8bdba0
> 
> # run pipeline
> /data/predict/tb571_lochness_test/run_synch.sh
> 
> # observe data trees
> tree tb571_lochness_test/RED-PHOENIX
> ```

I'd like to debug from the paths provided above. Can you give me read access to your .lochness.enc please?

**Comment by tashrifbillah** [comment]
Ha ha, after all the path adjustments I made, it looks like I missed the vital one! All set now.

For future, can you comment using `>` for a specific line? If we paste the whole past comment, the thread keeps getting bigger and harder to navigate by scroll. Thank you.

**Comment by kcho** [comment]
@tashrifbillah 

Would you mind giving me permission for the `min3-lochness`?


> conda create -y -n kcho-anon python=3.6

Line above returns
```
(base) [kc244@rgs10:/data/predict]$ conda create -y -n kcho-anon python=3.6
Collecting package metadata (current_repodata.json): failed

NotWritableError: The current user does not have write permissions to a required path.
  path: /data/predict/min3-lochness/pkgs/cache/9e0f62c3.json
```

**Comment by tashrifbillah** [comment]
Sorry about that, permission granted.

**Comment by kcho** [comment]
Hi @tashrifbillah,

There are two issues that prevent the `kcho/pronet` branch from working. 

1. Issue related with the site name: Since we are now using `{Study}{SiteCode}` pattern (eg. PronetLA), `_` between `FAKE_LA` will not work smoothly with the current version of `lochness`. So try using `PronetLA` rather than `FAKE_LA`

2. `API_TOKEN` requires to be in a format below
```
{                           
   lochness: {              
     REDCAP: {              
        PronetAD : {        
          redcap.Pronet : [ 
            Pronet          
         ]                  
       },                   
        PronetLA : {        
          redcap.Pronet : [ 
            Pronet          
         ]                  
       },                   
        PronetHK : {        
          redcap.Pronet : [ 
            Pronet          
         ]                  
       }                    
     },                     
     SECRETS: {             
        PronetAD :  *** ,   
        PronetLA :  *** ,   
        PronetHK :  ***     
     }                      
   },                       
redcap.Pronet: {
    "URL": "RedcapURL",
    "API_TOKEN": {
        "Pronet": "ApiToken"}
    }
}
```

I confirm that the survey files are being downloaded from the redcap, and there are files under GENERAL/raw, when the two points are changed.


## Here is how I'd test the `kcho/pronet` branch from scratch.
`/data/predict/tb571_lochness_test/test_template/test_create_lochness.sh`

```
conda create -y -n kcho-pronet python=3.6
conda activate kcho-pronet
pip install git+https://github.com/AMP-SCZ/lochness.git@kcho/pronet

out_dir=/data/predict/tb571_lochness_test/test_template/data_sync_test
lochness_create_template.py \
    --outdir ${out_dir} \
    --studies PronetLA PronetAD \
    --sources redcap \
    --email YourEmail \
    --poll_interval 86400 \
    --ssh_host rgs10.research.partners.org \
    --ssh_user YourID \
    --enter_password
```
This will ask you to enter the keyring information. (Ignore UPENN for now. Just skip by pressing enter.)

```
cd ${out_dir}
bash 1_encrypt_command.sh
bash 2_sync_command.sh
tree
```

Let me know if this works for you.

**Comment by tashrifbillah** [comment]
Which function does it take me to?

https://github.com/AMP-SCZ/dpanonymize/blob/49282b5c67ca1f88e7a651bc724e639b97e819d9/dpanonymize/__init__.py#L191

**Comment by tashrifbillah** [comment]
Hi Kevin, is this the block that should copy anonymized surveys to GENERAL?

https://github.com/AMP-SCZ/dpanonymize/blob/49282b5c67ca1f88e7a651bc724e639b97e819d9/dpanonymize/__init__.py#L63-L69

**Comment by tashrifbillah** [comment]
> There are two issues that prevent the kcho/pronet branch from working.
...
 I confirm that the survey files are being downloaded from the redcap, and there are files under GENERAL/raw, when the two points are changed.

No but I think I have found my reason. Just see your comment in the code below:

https://github.com/AMP-SCZ/dpanonymize/blob/49282b5c67ca1f88e7a651bc724e639b97e819d9/dpanonymize/surveys/__init__.py#L210-L211

My `pii_table` is empty! What goes in the `pii_table` noted in `config.yml`?

**Comment by tashrifbillah** [comment]
Found sample `pii_table`:

https://github.com/AMP-SCZ/dpanonymize/blob/49282b5c67ca1f88e7a651bc724e639b97e819d9/dpanonymize/surveys/__init__.py#L27-L34

**Comment by kcho** [comment]
> However, shouldn't they go under GENERAL/processed?
Whatever that was under `PROTECTED/raw` goes into `GENERAL/raw`, `PROTECTED/processed` goes into `GENERAL/processed`.

**Comment by kcho** [comment]
> Hi Kevin, is this the block that should copy anonymized surveys to GENERAL?

Yes.

**Comment by tashrifbillah** [comment]
Thank you for your second look at this. Now I have also tested dpanonymize for surveys 🗡️
