### ISSUE TITLE
Possible template errors

### ISSUE THREAD

**Issue by tashrifbillah** [AMP-SCZ/lochness#62]
1. Shouldn't the first one be `raw`?

https://github.com/AMP-SCZ/lochness/blob/759298eace405621a4091642f864431924b999f9/lochness/tree/__init__.py#L26-L29

2. Please double check these two templates:

https://github.com/AMP-SCZ/lochness/blob/759298eace405621a4091642f864431924b999f9/lochness/tree/__init__.py#L46-L49

https://github.com/AMP-SCZ/lochness/blob/759298eace405621a4091642f864431924b999f9/lochness/tree/__init__.py#L74-L77

I was expecting to see `hearing` and `mindlamp` words in them.

**Comment by tashrifbillah** [comment]
Also `**kwargs` should be removed from all of below:

https://github.com/AMP-SCZ/lochness/blob/759298eace405621a4091642f864431924b999f9/lochness/tree/__init__.py#L97-L118

**Comment by kcho** [comment]
**1. / 2. ** We are not using `behav_qc` or `hearing` datatype. Mindlamp goes under `phone` datatype. We can also change this folder name, which we need to discuss with Justin. 

> ``kwargs``

If you don't see any use of ``kwargs``, I'm up for removing this from our functions.

**Comment by tashrifbillah** [comment]
Can you answer my question `#1`?

**Comment by tashrifbillah** [comment]
Okay thank you.

**Comment by kcho** [comment]
> That said, we should push for hearing and mindlamp to go to their respective folders for the simplicity of coding.

1. We are not using `hearing` in AMP-SCZ project and this does not affect our pipeline.
2. For `mindlamp`, are you suggesting the `mindlamp` data to store data under `mindlamp` folder rather than the `phone` folder?

**Comment by tashrifbillah** [comment]
2. Yes.

**Comment by kcho** [comment]
I know Habib already started working on his pipeline according to `phone` directory name, we should confirm if this change will affect any other pipelines with the group. I have brought it up in the DPACC slack channel.
